export class Doc {
    id: string;
    returnId: string;
    objectProject: string;
    objectType: string;
    link: string[];
    modified: Date;
    created: Date;
    modifiedby: string;
    createdby: string[];
    state: string;
    derCount: number;
    derivates: string[];
    worldReadable: boolean;
    worldReadableComplete: boolean;
    category: string[];
    // category.top: string[];
    title: string[];
    place: string[];
    place_extended_search: string[];
    // place.type.gnd: string[];
    // cbuUnitTypes.actual: string;
    // ArchFile_class_001.leaf: string[];
    // ArchFile_class_001.root: string[];
    ArchFile_class_001: string[];
    component: string[];
    ArchFile_class_001_Label: string[];
    // ArchFile_class_001_Label.de: string[];
    // component.top: string[];
    // ArchFile_class_001.id.in.position.2: string;
    // cbuUnitTypes.root: string;
    cbuUnitTypes: string[];
    typeOfUnit: string[];
    facetObjectType: string;
    search_result_link_text: string;
    // search_result_link_text.de: string;
    // search_result_link_text.en: string;
    gnd: string[];
    version_: number;
}